name: Build & deploy site

on:
  push:
    paths:
      - mkdocs/**
      - tools/site-origin-cookie-scopes-visualizer/**
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Pages
        uses: actions/configure-pages@v5

      # mkdocs
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.3"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "mkdocs/pyproject.toml"

      - name: Build MkDocs
        working-directory: mkdocs/
        run: uv run mkdocs build

      # tool
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "^22.14.0"

      - name: Build tool
        working-directory: tools/site-origin-cookie-scopes-visualizer/
        run: npm ci && npm run build

      - name: Copy tool to MkDocs build output
        run: cp -r tools/site-origin-cookie-scopes-visualizer/dist/* mkdocs/site/site-origin-cookie-scopes-visualizer

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: mkdocs/site/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4