site_name: Cookies

plugins:
  - search:
      separator: >-
        [\s\-\–\—\―\.\,\;\"\'\/]+

nav:
  - About: index.md


theme:
  name: mkdocs
  # color_mode: auto
  # user_color_mode_toggle: true
  nav_style: light
  hljs_languages:
    - http
  navigation_depth: 6
  # shortcuts:   # defaults: help = ?, search = s, next = n, previous = p

markdown_extensions:
  # admonition usage: !!! note / info / warning / danger, newline, 4 spaces, text
  - admonition:
  - toc:
      permalink: "#"

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

strict: true
